import javafx.application.Application;
import javafx.stage.Stage;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Chub' at '19/01/16 14:03' with Gradle 2.10
 *
 * @author Chub, @date 19/01/16 14:03
 */
public class HelloJavaFx extends Application {

	@Override
	public void start(Stage stage) throws Exception {
	}
}
